import mongoose from 'mongoose';
import { MongoMemoryServer } from 'mongodb-memory-server';
import supertest from 'supertest';
import app from '../../server.js';
import User from '../../models/userModel.js';
import Product from '../../models/productModel.js';
import { stripeService } from '../../services/stripeService.js';
import { emailService } from '../../services/emailService.js';

// Mock services
jest.mock('../../services/stripeService.js', () => ({
  stripeService: {
    createCustomer: jest.fn().mockResolvedValue({ id: 'cus_mock123' }),
    createPaymentIntent: jest.fn().mockResolvedValue({
      id: 'pi_mock123',
      client_secret: 'pi_mock123_secret_123'
    }),
    createProduct: jest.fn().mockResolvedValue({ id: 'prod_mock123' }),
    createPrice: jest.fn().mockResolvedValue({ id: 'price_mock123' })
  }
}));

jest.mock('../../services/emailService.js', () => ({
  emailService: {
    sendWelcome: jest.fn().mockResolvedValue({}),
    sendPasswordReset: jest.fn().mockResolvedValue({})
  }
}));

jest.mock('jsonwebtoken', () => ({
  sign: jest.fn().mockReturnValue('mock_token'),
  verify: jest.fn().mockReturnValue({ id: 'user_mock_id' })
}));

// Create request object for supertest
const request = supertest(app);

describe('API Integration Tests', () => {
  let mongoServer;
  let token;
  let adminToken;
  let testProductId;

  // Set up MongoDB Memory Server and test data
  beforeAll(async () => {
    mongoServer = await MongoMemoryServer.create();
    const uri = mongoServer.getUri();
    
    // Override process.env.MONGODB_URI for the app to use the in-memory database
    process.env.MONGODB_URI = uri;
    
    // Create a regular user
    const regularUser = await User.create({
      name: 'Test User',
      email: 'test@example.com',
      password: 'password123',
      passwordConfirm: 'password123',
      stripeCustomerId: 'cus_mock123',
      emailVerified: true
    });
    
    // Create an admin user
    const adminUser = await User.create({
      name: 'Admin User',
      email: 'admin@example.com',
      password: 'password123',
      passwordConfirm: 'password123',
      role: 'admin',
      stripeCustomerId: 'cus_admin123',
      emailVerified: true
    });
    
    // Mock tokens for both users - normally these would be generated by the auth controller
    token = 'mock_token_regular_user';
    adminToken = 'mock_token_admin_user';
    
    // Create a test product
    const testProduct = await Product.create({
      name: 'Test Product',
      description: 'Test product description',
      price: 29.99,
      category: 'one-time',
      features: ['Feature 1', 'Feature 2'],
      stockQuantity: 10,
      stripeProductId: 'prod_mock123',
      stripePriceId: 'price_mock123'
    });
    
    testProductId = testProduct._id;
  });
  
  // Clean up after tests
  afterAll(async () => {
    await mongoose.disconnect();
    await mongoServer.stop();
  });
  
  // Authentication Tests
  describe('Authentication Routes', () => {
    it('should register a new user', async () => {
      const res = await request.post('/api/auth/register').send({
        name: 'New User',
        email: 'newuser@example.com',
        password: 'password123',
        passwordConfirm: 'password123'
      });
      
      expect(res.status).toBe(201);
      expect(res.body.status).toBe('success');
      expect(res.body.token).toBe('mock_token');
    });
    
    it('should login a user with correct credentials', async () => {
      const res = await request.post('/api/auth/login').send({
        email: 'test@example.com',
        password: 'password123'
      });
      
      expect(res.status).toBe(200);
      expect(res.body.status).toBe('success');
      expect(res.body.token).toBe('mock_token');
    });
    
    it('should reject login with incorrect credentials', async () => {
      const res = await request.post('/api/auth/login').send({
        email: 'test@example.com',
        password: 'wrongpassword'
      });
      
      expect(res.status).toBe(401);
      expect(res.body.status).toBe('fail');
    });
  });
  
  // Product Routes
  describe('Product Routes', () => {
    it('should get all products (public route)', async () => {
      const res = await request.get('/api/products');
      
      expect(res.status).toBe(200);
      expect(res.body.status).toBe('success');
      expect(res.body.data.products).toBeInstanceOf(Array);
      expect(res.body.data.products.length).toBeGreaterThan(0);
    });
    
    it('should get a specific product by ID (public route)', async () => {
      const res = await request.get(`/api/products/${testProductId}`);
      
      expect(res.status).toBe(200);
      expect(res.body.status).toBe('success');
      expect(res.body.data.product.name).toBe('Test Product');
    });
    
    it('should allow admin to create a new product', async () => {
      const res = await request
        .post('/api/products')
        .set('Authorization', `Bearer ${adminToken}`)
        .send({
          name: 'New Product',
          description: 'New product description',
          price: 39.99,
          category: 'one-time',
          features: ['Feature 1', 'Feature 2'],
          stockQuantity: 5
        });
      
      expect(res.status).toBe(201);
      expect(res.body.status).toBe('success');
      expect(res.body.data.product.name).toBe('New Product');
    });
    
    it('should not allow regular users to create products', async () => {
      const res = await request
        .post('/api/products')
        .set('Authorization', `Bearer ${token}`)
        .send({
          name: 'New Product',
          description: 'New product description',
          price: 39.99,
          category: 'one-time'
        });
      
      expect(res.status).toBe(403);
      expect(res.body.status).toBe('fail');
    });
  });
  
  // Order Routes
  describe('Order Routes', () => {
    it('should create an order for an authenticated user', async () => {
      const res = await request
        .post('/api/payment/create-order')
        .set('Authorization', `Bearer ${token}`)
        .send({
          products: [
            {
              productId: testProductId.toString(),
              quantity: 1
            }
          ],
          paymentMethod: 'stripe'
        });
      
      expect(res.status).toBe(201);
      expect(res.body.status).toBe('success');
      expect(res.body.data.order).toBeTruthy();
      expect(res.body.data.payment.clientSecret).toBeTruthy();
    });
    
    it('should get user orders for authenticated user', async () => {
      const res = await request
        .get('/api/orders/my-orders')
        .set('Authorization', `Bearer ${token}`);
      
      expect(res.status).toBe(200);
      expect(res.body.status).toBe('success');
      expect(res.body.data.orders).toBeInstanceOf(Array);
    });
    
    it('should not allow access to orders without authentication', async () => {
      const res = await request.get('/api/orders/my-orders');
      
      expect(res.status).toBe(401);
      expect(res.body.status).toBe('fail');
    });
  });
});